baseURL          =  "https://www.kaylegishen.com/"
languageCode     =  "en-us"
title            =  "Kayle Gishen"
theme            =  "papermod"
googleAnalytics  =  "UA-316110-8"

[markup.goldmark.renderer]
unsafe  =  true

[menu]
  [[menu.main]]
    identifier  =  "Contact"
    name        =  "Contact"
    url         =  "/contact/"
    weight      =  -110
  [[menu.main]]
    identifier  =  "Tags"
    name        =  "Tags"
    url         =  "/tags/"
    weight      =  -100

[params]
  defaultTheme     =  "light"
  layout           =  "archives"
  ShowReadingTime  =  true

  [params.homeInfoParams]
    title    =  "Hi there 👋"
    content  =  "I'm a Computer Scientist who loves to create simple solutions to hard problems and this is my blog."

  [[params.socialIcons]]
    name  =  "github"
    url   =  "https://github.com/kayleg"
  [[params.socialIcons]]
    name  =  "linkedin"
    url   =  "https://www.linkedin.com/in/kayle-gishen-561b823a/"

